--- #YAML:1.0
name:               Dancer-Plugin-Captcha-SecurityImage
version:            0.10
abstract:           Integration with GD::SecurityImage for your Dancer apps
author:
    - Alessandro Ranellucci <aar@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  6.31
build_requires:
    Dancer:  1.200
requires:
    Dancer:             1.200
    GD::SecurityImage:  0
resources:
    repository:  git://git@github.com:alexrj/Dancer-Plugin-Captcha-SecurityImage.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
